hmcts/terraform-module-application-backend

CODEOWNERS

DTSPO-658 Add Codeowners

---

config.tf
main.tf
provider.tf
secret.tf
variables.tf

DTSPO-658 Add module files

---

azure-pipelines.yml
ci/terraform-lint.tests.ps1
pipeline-templates/terraform-plan.yaml

DTSPO-658 Add pipeline and scripts

---

main.tf
provider.tf

DTSPO-658 Fix Provider Error

---

main.tf

DTSPO-658 Remove log_analytics data block

---

provider.tf

DTSPO-658 Comment out provider.tf

---

main.tf
variables.tf

DTSPO-658 Add log analytics config

---

main.tf

Dtspo 658 logs

---

provider.tf

DTSPO-658 Ammend provider.tf

---

azure-pipelines.yml
main.tf

DTSPO-658 Ammend main.tf

---

config.tf
main.tf
provider.tf
secret.tf
variables.tf

https://tools.hmcts.net/jira/browse/DTSPO-1355
```
[ ] Yes
[ x] No
```

updated to allow more than one gateway config

---

variables.tf

Remove variables not needed
```
[ ] Yes
[X] No
```

Remove unused variables

---

main.tf

https://tools.hmcts.net/jira/browse/DTSPO-658
Remove env Variable From Domain name
```
[ ] Yes
[x] No
```

DTSPO-658 Remove env Variable From Domain

---

main.tf

Reverts hmcts/terraform-module-application-backend#24

Revert "DTSPO-658 Remove env Variable From Domain"

---

.gitignore
data.tf
local.tf
main.tf
publicip.tf
secret.tf

https://tools.hmcts.net/jira/browse/DTSPO-658

DTSPO-658 Appliation gateway

---

README.md

Updated readme
```
[ ] Yes
[x] No
```

DTSPO-3187 - Readme Update

---

local.tf
main.tf
publicip.tf

Ensure compatibility with AzureRM provider versions 2.96.0 and above
```
[x] Yes
[ ] No
```

DTSPO-10835 - merge azurerm v3 branch

---

main.tf
variables.tf

https://tools.hmcts.net/jira/browse/DTSPO-13210
Added `ssl_policy` dynamic block so that we can choose which `policy_type` and `protocol_version` we can use, by default the variable would be `null`. 
```
[ ] Yes
[ X] No
```

added dynamic ssl policy

---

azure-pipelines.yml

Update azure-pipelines.yml to ubuntu-latest
```
[ ] Yes
[X] No
```

Update azure-pipelines.yml to ubuntu-latest

---

main.tf

Increase backend health beyond default liveness

---

main.tf

https://github.com/hmcts/sds-azure-platform/pull/575#issuecomment-1753135852
(and run `terraform fmt`)

Stop diff on every change

---

README.md
diagnostics.tf
variables.tf

Follow up to https://github.com/hmcts/terraform-module-applicationgateway/pull/6 and https://github.com/hmcts/terraform-module-frontdoor/pull/39
see also https://github.com/hmcts/terraform-module-applicationgateway/pull/15

Allow shipping logs to storage account to reduce costs

---

main.tf

add in rewriting of affinity cookie name

---

main.tf

extend module to handle rewrite rules

---

main.tf

condition not needed

---

main.tf

N/A
Added the ability to specify a request timeout above the default.

feat: specify request_timeout
